### ISSUE TITLE
kalibrate-bladerf did not show any result

### ISSUE THREAD

**Issue by 5eflabs** [Nuand/kalibrate-bladeRF#21]
Hi there,

I'm trying to run kalibrate-bladeRF on my x40, i tried to run it over GSM850 and GSM900 but still no result shown, even i tried with -m. here are some info relate with my stuff

./kal -s GSM850
Actual filter bandwidth = 1500 kHz
rxvga1 = 20 dB
rxvga2 = 30 dB
kal: Scanning for GSM-850 base stations.
GSM-850:
host@host:~/kalibrate-bladeRF/src$ ./kal -s GSM900
Actual filter bandwidth = 1500 kHz
rxvga1 = 20 dB
rxvga2 = 30 dB
kal: Scanning for GSM-900 base stations.
GSM-900:
bladeRF> version

  bladeRF-cli version:        1.8.0-git-29455d29
  libbladeRF version:         2.4.0-git-29455d29

  Firmware version:           2.4.0-git-a3d5c55f
  FPGA version:               0.11.0 (configured by USB host)

bladeRF> 

bladeRF> cal lms

  LPF tuning module: 25

  TX LPF I filter: 43
  TX LPF Q filter: 37

  RX LPF I filter: 21
  RX LPF Q filter: 11

  RX VGA2 DC reference module: 27
  RX VGA2 stage 1, I channel: 34
  RX VGA2 stage 1, Q channel: 30
  RX VGA2 stage 2, I channel: 29
  RX VGA2 stage 2, Q channel: 45

thank you for any help.

**Comment by rghilduta** [comment]
2G networks have become quite rare in recent years. It might be there are no GSM signals in those bands anymore.

**Comment by 5eflabs** [comment]
thank you for your reply Robert. I really appreciate it. regrding my issue, at first it was showing me some result both on GSM850 and GSM900 but suddenly it becomes no result each time i run it. and secondly, when i'm trying to run grgsm scanner, it gave me

[INFO] [UHD] linux; GNU C++ version 10.2.1 20201207; Boost_107400; UHD_3.15.0.0-4+b1
[ERROR] avahi_service_browser_new() failed: Bad state
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.8.2.0
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
[bladeRF common] init: DEBUG: entering initialization
[bladeRF source] init: Opening Nuand bladeRF with device identifier string '*:instance=0'
[INFO @ host/libraries/libbladeRF/src/helpers/version.c:79] Firmware version (v2.4.0) is newer than entries in libbladeRF's compatibility table. Please update libbladeRF if problems arise.
[bladeRF source] Device: Nuand bladeRF Serial # 3526...5d5c FW v2.4.0 FPGA v0.10.2
[bladeRF source] init: Buffers: 512, samples per buffer: 4096, active transfers: 32
[bladeRF source] bladerf_source_c: Warning: number of channels specified on command line (4) is greater than the maximum number supported by this device (1). Resetting to 1.
[bladeRF source] bladerf_source_c: DEBUG: initialization complete
[bladeRF source] set_dc_offset_mode: Automatic DC correction mode is not implemented.
[WARNING @ host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c:1705] RX DC calibration table not found. Manual gain control will be used instead.
[INFO @ host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c:1706] To enable AGC, see "Generating a DC offset table" at https://github.com/Nuand/bladeRF/wiki/DC-offset-and-IQ-Imbalance-Correction
Traceback (most recent call last):
  File "/home/kali/gr-gsm/apps/grgsm_scanner", line 438, in <module>
    main()
  File "/home/kali/gr-gsm/apps/grgsm_scanner", line 434, in main
    do_scan(options.samp_rate, options.band, options.speed,
  File "/home/kali/gr-gsm/apps/grgsm_scanner", line 330, in do_scan
    scanner = wideband_scanner(rec_len=6 - speed,
  File "/home/kali/gr-gsm/apps/grgsm_scanner", line 228, in __init__
    self.rtlsdr_source.set_gain_mode(True, 0)
  File "/usr/lib/python3/dist-packages/osmosdr/osmosdr_swig.py", line 1861, in set_gain_mode
    return _osmosdr_swig.source_sptr_set_gain_mode(self, automatic, chan)
RuntimeError: set_gain_mode: Setting gain mode to 'automatic' failed: Operation not supported (-8)

again thank you very much for any helps.
